{% set name = "hexwatershed" %}
{% set version = "0.2.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hexwatershed-{{ version }}.tar.gz
  sha256: 74a183199e5e3b7464e43f10c6df82ca5568c3df9cdb1c69e1c650ff040d00ef

build:  
  noarch: python
  script:
    - python setup.py build_external 
    - python setup.py install
  number: 0

requirements:  
  
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
    - python >=3.8    
    - packaging
    - setuptools
  
  host:
    - python >=3.8  
    - {{ compiler('cxx') }}
 
  run:
    - python >=3.8
    - numpy
    - matplotlib-base
    - gdal
    - pyflowline

test:
  imports:
    - pyhexwatershed
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/changliao1025/pyhexwatershed
  summary: A mesh-independent flow direction model for hydrologic models
  license: BSD-2-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - changliao1025
