{% set name = "hexwatershed" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hexwatershed-{{ version }}.tar.gz
  sha256: df91ded9dd32075c30df7a24300d3a979f78114a2c6d6530115ad8254f16a8f3

build:
  host:
    platform: linux-64
  script:
    - python setup.py build_external 
  # Build the package for macOS (64-bit)
  host:
    platform: osx-64
  script:
    - python setup.py build_external 
  host:
    platform: win-64
  script:
    - python setup.py build_external 

requirements:
  host:
    - linux-64
    - osx-64
    - win-64
  build:
    - python    
    - packaging
    - setuptool
  run:
    - python
    - packaging
    - numpy
    - matplotlib
    - gdal
    - pyflowline

test:
  imports:
    - pyhexwatershed
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/changliao1025/pyhexwatershed
  summary: A mesh independent flow direction model for hydrologic models
  license: BSD-2-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - changliao1025
