{% set name = "hexwatershed" %}
{% set version = "0.2.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hexwatershed-{{ version }}.tar.gz
  sha256: 75b0ed8bc1ee212e1c0afc32c967f3251c8dae867420bcefcde208801ce25220

build:  
  noarch: python
  script:
    - python setup.py build_external 
    - {{ PYTHON }} -m pip install . -vv
  number: 0


requirements:  
  
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
    - python >=3.8    
    - packaging
    - setuptools
    - pip
  
  host:
    - python >=3.8  
    - pip
    - packaging
    - {{ compiler('cxx') }}
 
  run:
    - python >=3.8
    - numpy
    - matplotlib-base
    - gdal
    - pyflowline

test:
  imports:
    - pyhexwatershed
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/changliao1025/pyhexwatershed
  summary: A mesh-independent flow direction model for hydrologic models
  license: BSD-2-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - changliao1025
